CREATE DATABASE IF NOT EXISTS pet CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'pet'@'localhost' IDENTIFIED BY 'pet';
CREATE USER IF NOT EXISTS 'pet'@'127.0.0.1' IDENTIFIED BY 'pet';

GRANT ALL PRIVILEGES ON pet.* TO 'pet'@'localhost';
GRANT ALL PRIVILEGES ON pet.* TO 'pet'@'127.0.0.1';

FLUSH PRIVILEGES;
